# Generated by Django 6.0.4 on 2026-05-02 20:52

from django.db import migrations, models


def remap_brain_space_forwards(apps, schema_editor) -> None:
    """Map legacy low/medium/high stored values before AlterField choices change."""
    Task = apps.get_model("mindflow", "Task")
    CapacitySignal = apps.get_model("mindflow", "CapacitySignal")
    old_to_new = {
        "low": "quick-fix",
        "medium": "admin",
        "high": "hyperfocus",
    }
    for old, new in old_to_new.items():
        Task.objects.filter(brain_space_level=old).update(brain_space_level=new)
        CapacitySignal.objects.filter(brain_space_level=old).update(brain_space_level=new)


def remap_brain_space_reverse(apps, schema_editor) -> None:
    """Approximate reverse mapping for rollback (many-to-one)."""
    Task = apps.get_model("mindflow", "Task")
    CapacitySignal = apps.get_model("mindflow", "CapacitySignal")
    new_to_old = {
        "admin": "medium",
        "creative": "medium",
        "social": "medium",
        "quick-fix": "low",
        "hyperfocus": "high",
    }
    for new, old in new_to_old.items():
        Task.objects.filter(brain_space_level=new).update(brain_space_level=old)
        CapacitySignal.objects.filter(brain_space_level=new).update(brain_space_level=old)


class Migration(migrations.Migration):

    dependencies = [
        ('mindflow', '0002_phase1_domain_models'),
    ]

    operations = [
        migrations.RunPython(remap_brain_space_forwards, remap_brain_space_reverse),
        migrations.RemoveField(
            model_name='task',
            name='friction_level',
        ),
        migrations.AlterField(
            model_name='capacitysignal',
            name='brain_space_level',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('creative', 'Creative'), ('social', 'Social'), ('quick-fix', 'Quick fix'), ('hyperfocus', 'Hyperfocus')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='brain_space_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('creative', 'Creative'), ('social', 'Social'), ('quick-fix', 'Quick fix'), ('hyperfocus', 'Hyperfocus')], default='quick-fix', max_length=16),
        ),
    ]
